import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const args = Object.fromEntries(process.argv.slice(2).map((v,i,a)=>v.startsWith('--')?[v.slice(2),a[i+1]&&!a[i+1].startsWith('--')?a[i+1]:true]:null).filter(Boolean));
const queuePath = path.resolve(args.queue || process.env.SOCIAL_QUEUE || 'content/social-queue.json');
const statePath = path.resolve(args.state || process.env.SOCIAL_STATE || 'content/social-state.json');
const now = new Date(args.now || Date.now());
const dryRun = args['dry-run'] === true || process.env.DRY_RUN === 'true';
const maxPosts = Number(args.limit || process.env.MAX_POSTS_PER_RUN || 10);
const readJson = (p, fallback) => fs.existsSync(p) ? JSON.parse(fs.readFileSync(p,'utf8')) : fallback;
const writeJsonAtomic = (p, value) => { fs.mkdirSync(path.dirname(p),{recursive:true}); const t=p+'.tmp'; fs.writeFileSync(t,JSON.stringify(value,null,2)+'\n'); fs.renameSync(t,p); };
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const hash = v => crypto.createHash('sha256').update(v).digest('hex').slice(0,20);
function validate(post){ const missing=[]; for(const k of ['platform','scheduled_at','text']) if(!post[k]) missing.push(k); if(missing.length) throw new Error(`missing ${missing.join(', ')}`); if(!['linkedin','instagram','facebook','buffer'].includes(post.platform)) throw new Error(`unsupported platform ${post.platform}`); if(Number.isNaN(Date.parse(post.scheduled_at))) throw new Error('scheduled_at must be ISO-8601'); if(post.platform==='instagram' && !post.media_url) throw new Error('Instagram requires a public media_url'); }
async function request(url, options={}, attempts=3){ let last; for(let i=1;i<=attempts;i++){ try{ const res=await fetch(url,options); const text=await res.text(); let body; try{body=text?JSON.parse(text):{};}catch{body={raw:text};} if(res.ok) return body; const e=new Error(`HTTP ${res.status}: ${text.slice(0,500)}`); e.status=res.status; throw e; }catch(e){ last=e; if(i<attempts && (!e.status || e.status===429 || e.status>=500)) await sleep(1000*2**(i-1)); else break; }} throw last; }
async function publishLinkedIn(post){ const token=process.env.LINKEDIN_ACCESS_TOKEN, author=process.env.LINKEDIN_AUTHOR_URN; if(!token||!author) throw new Error('LINKEDIN_ACCESS_TOKEN and LINKEDIN_AUTHOR_URN are required'); const body={author,lifecycleState:'PUBLISHED',specificContent:{'com.linkedin.ugc.ShareContent':{shareCommentary:{text:post.text},shareMediaCategory:post.media_url?'ARTICLE':'NONE',...(post.media_url?{media:[{status:'READY',originalUrl:post.media_url,title:{text:post.title||'Mission GroundWork'}}]}:{})}},visibility:{'com.linkedin.ugc.MemberNetworkVisibility':post.visibility||'PUBLIC'}}; return request('https://api.linkedin.com/v2/ugcPosts',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','X-Restli-Protocol-Version':'2.0.0'},body:JSON.stringify(body)}); }
async function publishFacebook(post){ const token=process.env.META_PAGE_ACCESS_TOKEN, page=process.env.META_PAGE_ID; if(!token||!page) throw new Error('META_PAGE_ACCESS_TOKEN and META_PAGE_ID are required'); const endpoint=post.media_url?`${page}/photos`:`${page}/feed`; const params=new URLSearchParams({access_token:token,message:post.text}); if(post.media_url) params.set('url',post.media_url); return request(`https://graph.facebook.com/v23.0/${endpoint}`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params}); }
async function publishInstagram(post){ const token=process.env.META_PAGE_ACCESS_TOKEN, ig=process.env.INSTAGRAM_BUSINESS_ID; if(!token||!ig) throw new Error('META_PAGE_ACCESS_TOKEN and INSTAGRAM_BUSINESS_ID are required'); const create=new URLSearchParams({access_token:token,image_url:post.media_url,caption:post.text}); const container=await request(`https://graph.facebook.com/v23.0/${ig}/media`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:create}); const publish=new URLSearchParams({access_token:token,creation_id:container.id}); return request(`https://graph.facebook.com/v23.0/${ig}/media_publish`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:publish}); }
async function publishBuffer(post){ const token=process.env.BUFFER_ACCESS_TOKEN, profile=post.profile_id||process.env.BUFFER_PROFILE_ID; if(!token||!profile) throw new Error('BUFFER_ACCESS_TOKEN and BUFFER_PROFILE_ID are required'); const form=new URLSearchParams({access_token:token,text:post.text,profile_ids:profile,now:'true'}); if(post.media_url) form.set('media[photo]',post.media_url); return request('https://api.bufferapp.com/1/updates/create.json',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form}); }
const publishers={linkedin:publishLinkedIn,facebook:publishFacebook,instagram:publishInstagram,buffer:publishBuffer};
const queue=readJson(queuePath,[]); const state=readJson(statePath,{published:{},failed:{},last_run:null}); if(!Array.isArray(queue)) throw new Error('Queue must be a JSON array'); let processed=0, changed=false;
for(const post of queue){ try{ validate(post); }catch(e){ console.error(`[invalid] ${post.id||'unknown'}: ${e.message}`); continue; } const id=post.id||hash(`${post.platform}|${post.scheduled_at}|${post.text}|${post.media_url||''}`); if(state.published[id]) continue; if(new Date(post.scheduled_at)>now) continue; if(processed>=maxPosts) break; processed++; try{ if(dryRun){ console.log(`[dry-run] ${id} -> ${post.platform}: ${post.text.slice(0,100)}`); continue; } const result=await publishers[post.platform](post); state.published[id]={platform:post.platform,scheduled_at:post.scheduled_at,published_at:new Date().toISOString(),result}; delete state.failed[id]; changed=true; console.log(`[published] ${id} -> ${post.platform}`); }catch(e){ const prev=state.failed[id]?.attempts||0; state.failed[id]={platform:post.platform,attempts:prev+1,last_attempt:new Date().toISOString(),error:e.message}; changed=true; console.error(`[failed] ${id} -> ${post.platform}: ${e.message}`); }}
if(processed>0){
  state.last_run={at:new Date().toISOString(),due_processed:processed,dry_run:dryRun};
  if(changed||!dryRun) writeJsonAtomic(statePath,state);
}
console.log(JSON.stringify({queue:queue.length,processed,published:Object.keys(state.published).length,failed:Object.keys(state.failed).length,dryRun},null,2));
